project:
  type: website

website:
  description: "A blog built with Quarto"

  favicon: images/logo.svg

  site-url: https://rohan-reddy.github.io # you must change this appropriately for RSS feeds to work properly
  
  # New line with typeset logo:
  title: "Rohan Reddy / Notes"

  navbar:
    logo: images/logo.svg

    right:
      - about.qmd
      - icon: github
        href: https://github.com/rohan-reddy
  
  page-footer: 
    left: "Â© 2026 Rohan Reddy"
    right: "Built with Quarto"
  

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    
    # THE MAGIC SAUCE: This moves all notes to the side margin
    reference-location: margin
    citation-location: margin
    cap-location: margin  # Moves figure captions to the margin
    
    # The key Distill features:
    citations-hover: true
    footnotes-hover: true

    css: styles.css     # For fine-tuning fonts



